"""Explicit Xiaomi MiBLE local activation and login state machine."""

from __future__ import annotations

import asyncio
import hmac
import logging
import secrets
import string
from dataclasses import dataclass
from enum import Enum, auto
from typing import Any

from cryptography.hazmat.primitives.asymmetric import ec

from .const import (
    MIBLE_CHAR_10,
    MIBLE_CHAR_19,
    PROTOCOL_STAGE_TIMEOUT,
)
from .crypto import (
    LoginMaterial,
    derive_login_material,
    derive_setup_material,
    encrypt_device_id,
    generate_p256_private_key,
    p256_public_key_bytes,
    p256_shared_secret,
)
from .models import DeviceCredentials

_LOGGER = logging.getLogger(__name__)


class MiBLEError(Exception):
    """Base protocol exception."""


class MiBLETimeoutError(MiBLEError):
    """A protocol stage timed out."""


class MiBLEActivationError(MiBLEError):
    """Registration was rejected."""


class MiBLEAuthenticationError(MiBLEError):
    """Mutual login authentication failed."""


class UnsupportedMiBLEDeviceError(MiBLEError):
    """Required MiBLE characteristics are unavailable."""


class InvalidProtocolResponseError(MiBLEError):
    """A notification was malformed or arrived in an invalid state."""


class DisconnectedError(MiBLEError):
    """The BLE link was lost before the exchange completed."""


class Phase(Enum):
    """Fine-grained states from the working browser activation flow."""

    IDLE = auto()
    WAIT_ACTIVATION_STATUS = auto()
    WAIT_FRESH_MARKER = auto()
    WAIT_EXISTING_ID_1 = auto()
    WAIT_EXISTING_ID_2 = auto()
    WAIT_PUBLIC_KEY_REQUEST = auto()
    WAIT_DEVICE_PUBLIC_KEY = auto()
    WAIT_DID_REQUEST = auto()
    WAIT_DID_ACK = auto()
    WAIT_ACTIVATION_RESULT = auto()
    LOGIN_WAIT_READY = auto()
    LOGIN_WAIT_RANDOM_ACCEPTED = auto()
    LOGIN_WAIT_DEVICE_RANDOM = auto()
    LOGIN_WAIT_DEVICE_PROOF_REQUEST = auto()
    LOGIN_WAIT_DEVICE_PROOF = auto()
    LOGIN_WAIT_CLIENT_PROOF_REQUEST = auto()
    LOGIN_WAIT_RESULT = auto()
    COMPLETE = auto()
    FAILED = auto()


@dataclass(frozen=True, slots=True)
class ProtocolWrite:
    """One write generated by the pure state machine."""

    characteristic: str
    data: bytes


def _w10(value: str) -> ProtocolWrite:
    return ProtocolWrite(MIBLE_CHAR_10, bytes.fromhex(value))


def _w19(value: bytes | str) -> ProtocolWrite:
    return ProtocolWrite(
        MIBLE_CHAR_19, bytes.fromhex(value) if isinstance(value, str) else value
    )


def _fragments(data: bytes, size: int = 18) -> list[ProtocolWrite]:
    return [
        _w19(bytes((index + 1, 0)) + data[start : start + size])
        for index, start in enumerate(range(0, len(data), size))
    ]


def generate_device_id() -> bytes:
    """Generate the 20-byte DID shape used by Xiaomi's working setup flow."""

    alphabet = string.ascii_letters + string.digits
    suffix = "".join(secrets.choice(alphabet) for _ in range(6)).encode()
    return b"\x00blt.3.129v" + suffix + b"ATC"


class MiBLEStateMachine:
    """Pure activation/login state machine driven by GATT notifications."""

    def __init__(
        self,
        *,
        private_key: ec.EllipticCurvePrivateKey | None = None,
        client_random: bytes | None = None,
        device_id: bytes | None = None,
        token: bytes | None = None,
    ) -> None:
        self.phase = Phase.IDLE
        self.private_key = private_key or generate_p256_private_key()
        self.public_key = p256_public_key_bytes(self.private_key)
        self.client_random = client_random or secrets.token_bytes(16)
        if len(self.client_random) != 16:
            raise ValueError("client random must be 16 bytes")
        self.device_id = device_id or generate_device_id()
        self._provided_token = token
        self._device_public_parts: dict[int, bytes] = {}
        self._existing_id_parts: dict[int, bytes] = {}
        self._device_proof_parts: dict[int, bytes] = {}
        self._credentials: DeviceCredentials | None = None
        self._login: LoginMaterial | None = None
        self.was_activated = False

    @property
    def credentials(self) -> DeviceCredentials:
        """Return verified credentials only after successful login."""

        if self.phase is not Phase.COMPLETE or self._credentials is None:
            raise MiBLEAuthenticationError("credentials have not been verified")
        return self._credentials

    @property
    def complete(self) -> bool:
        return self.phase is Phase.COMPLETE

    def start_activation(self) -> list[ProtocolWrite]:
        """Start local registration (the reference command a2000000)."""

        if self.phase is not Phase.IDLE:
            raise InvalidProtocolResponseError("state machine has already started")
        self.phase = Phase.WAIT_ACTIVATION_STATUS
        return [_w10("a2000000")]

    def start_login(self, token: bytes | None = None) -> list[ProtocolWrite]:
        """Start login with an existing 12-byte token."""

        actual_token = token or self._provided_token
        if actual_token is None or len(actual_token) != 12:
            raise ValueError("login requires a 12-byte Mi token")
        self._provided_token = actual_token
        self.phase = Phase.LOGIN_WAIT_READY
        return [_w10("24000000"), _w19("0000000b0100")]

    def feed(self, characteristic: str, value: bytes) -> list[ProtocolWrite]:
        """Consume one notification and return ordered GATT writes."""

        characteristic = characteristic.lower()
        safe_statuses = {
            bytes.fromhex(item)
            for item in (
                "12000000",
                "11000000",
                "23000000",
                "21000000",
                "000000000100",
                "000000000200",
                "010001000000",
                "00000101",
                "00000100",
                "000001050100",
                "000000030400",
                "0000000d0100",
                "0000000c0200",
            )
        }
        detail = (
            value.hex()
            if value in safe_statuses
            else (
                f"fragment={value[0] if value else 'empty'} length={len(value)} "
                "(content redacted)"
            )
        )
        _LOGGER.debug(
            "MiBLE state %s received %s status %s",
            self.phase.name.lower(),
            characteristic[-8:],
            detail,
        )
        if characteristic == MIBLE_CHAR_10:
            return self._feed_control(value)
        if characteristic != MIBLE_CHAR_19:
            raise InvalidProtocolResponseError(
                "notification from unknown characteristic"
            )
        return self._feed_transfer(value)

    def disconnected(self) -> None:
        """Fail an in-flight exchange on disconnect."""

        if self.phase not in (Phase.IDLE, Phase.COMPLETE, Phase.FAILED):
            self.phase = Phase.FAILED
            raise DisconnectedError("device disconnected during MiBLE exchange")

    def _feed_control(self, value: bytes) -> list[ProtocolWrite]:
        if value == bytes.fromhex("12000000"):
            self.phase = Phase.FAILED
            raise MiBLEActivationError("device rejected local activation")
        if value == bytes.fromhex("23000000"):
            self.phase = Phase.FAILED
            raise MiBLEAuthenticationError("device rejected MiBLE login")
        if value == bytes.fromhex("11000000"):
            if self.phase is not Phase.WAIT_ACTIVATION_RESULT:
                raise InvalidProtocolResponseError("unexpected activation success")
            _LOGGER.debug("MiBLE activation confirmed; starting login verification")
            assert self._credentials is not None
            return self.start_login(self._credentials.token)
        if value == bytes.fromhex("21000000"):
            if self.phase is not Phase.LOGIN_WAIT_RESULT:
                raise InvalidProtocolResponseError("unexpected login success")
            self.phase = Phase.COMPLETE
            _LOGGER.debug("MiBLE login confirmed")
            return []
        raise InvalidProtocolResponseError(
            f"unexpected control response {value.hex()} in {self.phase.name}"
        )

    def _begin_key_exchange(self) -> list[ProtocolWrite]:
        self.phase = Phase.WAIT_PUBLIC_KEY_REQUEST
        return [_w19("00000100"), _w10("15000000"), _w19("000000030400")]

    def _feed_transfer(self, value: bytes) -> list[ProtocolWrite]:
        if value == bytes.fromhex("000001050100"):
            self.phase = Phase.FAILED
            raise MiBLETimeoutError("device reported activation timeout")

        if self.phase is Phase.WAIT_ACTIVATION_STATUS:
            if value == bytes.fromhex("000000000100"):
                self.was_activated = False
                self.phase = Phase.WAIT_FRESH_MARKER
                return [_w19("00000101")]
            if value == bytes.fromhex("000000000200"):
                self.was_activated = True
                self.phase = Phase.WAIT_EXISTING_ID_1
                return [_w19("00000101")]

        if self.phase is Phase.WAIT_FRESH_MARKER and value == bytes.fromhex(
            "010001000000"
        ):
            return self._begin_key_exchange()

        if self.phase is Phase.WAIT_EXISTING_ID_1 and value.startswith(b"\x01\x00"):
            self._existing_id_parts[1] = value[2:]
            self.phase = Phase.WAIT_EXISTING_ID_2
            return []
        if self.phase is Phase.WAIT_EXISTING_ID_2 and value.startswith(b"\x02\x00"):
            self._existing_id_parts[2] = value[2:]
            existing = self._existing_id_parts[1] + self._existing_id_parts[2]
            if len(existing) <= 4:
                raise InvalidProtocolResponseError("existing DID response is too short")
            self.device_id = existing[4:]
            return self._begin_key_exchange()

        if self.phase is Phase.WAIT_PUBLIC_KEY_REQUEST and value == bytes.fromhex(
            "00000101"
        ):
            self.phase = Phase.WAIT_DEVICE_PUBLIC_KEY
            return _fragments(self.public_key[1:])

        if value == bytes.fromhex("000000030400") and self.phase in (
            Phase.WAIT_PUBLIC_KEY_REQUEST,
            Phase.WAIT_DEVICE_PUBLIC_KEY,
        ):
            return [_w19("00000101")]

        if self.phase is Phase.WAIT_DEVICE_PUBLIC_KEY and len(value) >= 3:
            index = value[0]
            if value[1] != 0 or index not in (1, 2, 3, 4):
                raise InvalidProtocolResponseError("invalid public-key fragment")
            self._device_public_parts[index] = value[2:]
            if index != 4:
                return []
            if set(self._device_public_parts) != {1, 2, 3, 4}:
                raise InvalidProtocolResponseError("missing device public-key fragment")
            peer = b"\x04" + b"".join(
                self._device_public_parts[i] for i in range(1, 5)
            )
            if len(peer) != 65:
                raise InvalidProtocolResponseError("device public key has wrong length")
            try:
                setup = derive_setup_material(
                    p256_shared_secret(self.private_key, peer)
                )
            except ValueError as err:
                raise InvalidProtocolResponseError(
                    "invalid device P-256 public key"
                ) from err
            encrypted_did = encrypt_device_id(self.device_id, setup.device_id_key)
            self._credentials = DeviceCredentials(
                token=setup.token, bindkey=setup.bindkey, device_id=self.device_id
            )
            self._encrypted_did = encrypted_did
            self.phase = Phase.WAIT_DID_REQUEST
            _LOGGER.debug("MiBLE setup keys derived (secret material redacted)")
            return [_w19("00000100"), _w19("000000000200")]

        if self.phase is Phase.WAIT_DID_REQUEST and value == bytes.fromhex("00000101"):
            self.phase = Phase.WAIT_DID_ACK
            return _fragments(self._encrypted_did)

        if self.phase is Phase.WAIT_DID_ACK and value == bytes.fromhex("00000100"):
            self.phase = Phase.WAIT_ACTIVATION_RESULT
            return [_w10("13000000")]

        if self.phase is Phase.LOGIN_WAIT_READY and value == bytes.fromhex("00000101"):
            self.phase = Phase.LOGIN_WAIT_RANDOM_ACCEPTED
            return [_w19(b"\x01\x00" + self.client_random)]

        if self.phase is Phase.LOGIN_WAIT_RANDOM_ACCEPTED and value == bytes.fromhex(
            "0000000d0100"
        ):
            self.phase = Phase.LOGIN_WAIT_DEVICE_RANDOM
            return [_w19("00000101")]

        if self.phase is Phase.LOGIN_WAIT_DEVICE_RANDOM and value.startswith(
            b"\x01\x00"
        ):
            device_random = value[2:]
            if len(device_random) != 16:
                raise InvalidProtocolResponseError("device random has wrong length")
            assert self._provided_token is not None
            self._login = derive_login_material(
                self._provided_token, self.client_random, device_random
            )
            self.phase = Phase.LOGIN_WAIT_DEVICE_PROOF_REQUEST
            return [_w19("00000100")]

        if (
            self.phase is Phase.LOGIN_WAIT_DEVICE_PROOF_REQUEST
            and value == bytes.fromhex("0000000c0200")
        ):
            self.phase = Phase.LOGIN_WAIT_DEVICE_PROOF
            return [_w19("00000101")]

        if self.phase is Phase.LOGIN_WAIT_DEVICE_PROOF and len(value) >= 3:
            index = value[0]
            if value[1] != 0 or index not in (1, 2):
                raise InvalidProtocolResponseError("invalid device-proof fragment")
            self._device_proof_parts[index] = value[2:]
            if index == 1:
                return []
            if set(self._device_proof_parts) != {1, 2}:
                raise InvalidProtocolResponseError("missing device-proof fragment")
            proof = self._device_proof_parts[1] + self._device_proof_parts[2]
            assert self._login is not None
            if len(proof) != 32 or not hmac.compare_digest(
                proof, self._login.expected_device_proof
            ):
                self.phase = Phase.FAILED
                raise MiBLEAuthenticationError("device login proof did not verify")
            self.phase = Phase.LOGIN_WAIT_CLIENT_PROOF_REQUEST
            return [_w19("00000100"), _w19("0000000a0200")]

        if (
            self.phase is Phase.LOGIN_WAIT_CLIENT_PROOF_REQUEST
            and value == bytes.fromhex("00000101")
        ):
            assert self._login is not None
            self.phase = Phase.LOGIN_WAIT_RESULT
            return _fragments(self._login.client_proof)

        raise InvalidProtocolResponseError(
            f"unexpected transfer response {value.hex()} in {self.phase.name}"
        )


async def run_state_machine(
    client: Any,
    machine: MiBLEStateMachine,
    initial_writes: list[ProtocolWrite],
    *,
    stage_timeout: float = PROTOCOL_STAGE_TIMEOUT,
    disconnected_event: asyncio.Event | None = None,
) -> None:
    """Drive the pure state machine over a connected BleakClient."""

    queue: asyncio.Queue[tuple[str, bytes] | None] = asyncio.Queue()
    loop = asyncio.get_running_loop()

    def notification(characteristic: Any, data: bytearray) -> None:
        uuid = str(getattr(characteristic, "uuid", characteristic)).lower()
        loop.call_soon_threadsafe(queue.put_nowait, (uuid, bytes(data)))

    async def next_notification() -> tuple[str, bytes] | None:
        if disconnected_event is None:
            return await queue.get()
        notification_task = asyncio.create_task(queue.get())
        disconnect_task = asyncio.create_task(disconnected_event.wait())
        try:
            done, _pending = await asyncio.wait(
                (notification_task, disconnect_task),
                return_when=asyncio.FIRST_COMPLETED,
            )
            if disconnect_task in done and disconnect_task.result():
                return None
            return notification_task.result()
        finally:
            for task in (notification_task, disconnect_task):
                if not task.done():
                    task.cancel()
            await asyncio.gather(
                notification_task, disconnect_task, return_exceptions=True
            )

    started: list[str] = []
    try:
        for uuid in (MIBLE_CHAR_10, MIBLE_CHAR_19):
            await client.start_notify(uuid, notification)
            started.append(uuid)
        for write in initial_writes:
            await client.write_gatt_char(
                write.characteristic, write.data, response=True
            )
        while not machine.complete:
            try:
                async with asyncio.timeout(stage_timeout):
                    if disconnected_event is None:
                        item = await queue.get()
                    else:
                        item = await next_notification()
            except TimeoutError as err:
                raise MiBLETimeoutError(
                    f"timeout in MiBLE state {machine.phase.name.lower()}"
                ) from err
            if item is None:
                machine.disconnected()
                raise DisconnectedError("device disconnected")
            characteristic, value = item
            for write in machine.feed(characteristic, value):
                await client.write_gatt_char(
                    write.characteristic, write.data, response=True
                )
    finally:
        for uuid in reversed(started):
            try:
                await client.stop_notify(uuid)
            except Exception:  # best effort cleanup after a broken link
                _LOGGER.debug(
                    "Could not stop MiBLE notification %s", uuid, exc_info=True
                )


async def activate(
    client: Any, disconnected_event: asyncio.Event | None = None
) -> DeviceCredentials:
    """Provision new local credentials and prove them with a subsequent login."""

    machine = MiBLEStateMachine()
    await run_state_machine(
        client,
        machine,
        machine.start_activation(),
        disconnected_event=disconnected_event,
    )
    return machine.credentials


async def login(
    client: Any, token: bytes, disconnected_event: asyncio.Event | None = None
) -> None:
    """Authenticate an active GATT connection with an existing token."""

    machine = MiBLEStateMachine(token=token)
    await run_state_machine(
        client,
        machine,
        machine.start_login(),
        disconnected_event=disconnected_event,
    )
